import type { ConsultAdvice, ConsultCategory, ConsultSeverity } from '../types';

export const consultCategoryLabels: Record<ConsultCategory, string> = {
  stance: 'スタンス',
  grip: 'グリップ',
  takeback: 'テイクバック',
  release: 'リリース',
  followThrough: 'フォロースルー',
  aiming: '狙い方',
  rhythm: 'リズム',
  mental: 'メンタル',
  yips: 'イップス',
  practicePlan: '練習計画',
  other: 'その他',
};

export const consultSeverityLabels: Record<ConsultSeverity, string> = {
  light: '軽い違和感',
  normal: 'よく起きる',
  serious: 'かなり困っている',
};

type AdviceSeed = Omit<ConsultAdvice, 'symptoms' | 'possibleCauses' | 'checkPoints'> & {
  symptoms?: string[];
  possibleCauses?: string[];
  checkPoints?: string[];
};

function advice(seed: AdviceSeed): ConsultAdvice {
  return {
    symptoms: ['再現性が下がる', '狙いよりズレる'],
    possibleCauses: ['確認項目が多い', '力みで動作が変わる'],
    checkPoints: ['1投ごとに同じ準備ができたか', '外れ方が同じ方向に偏るか'],
    severity: 'normal',
    ...seed,
  };
}

export const consultAdvice: ConsultAdvice[] = [
  advice({
    id: 'stance-001',
    category: 'stance',
    title: '足位置が毎回ずれる',
    problemKeywords: ['足', '立ち位置', 'ずれる'],
    adviceSummary: '足元の再現性を先に固定し、狙いの修正を後回しにしましょう。',
    recommendedPracticeMenuIds: [
      'beginner-stance-three-sets',
      'intermediate-stance-pressure-count-up',
    ],
    relatedKnowledgeIds: ['kb-stance-setup', 'kb-routine-one-breath'],
  }),
  advice({
    id: 'stance-002',
    category: 'stance',
    title: '前後に体が揺れる',
    problemKeywords: ['揺れる', '重心', '前のめり'],
    possibleCauses: ['重心移動が大きい', '投げる前に急いでいる'],
    adviceSummary: '投げる前に足裏の圧を確認し、体重移動を小さくします。',
    recommendedPracticeMenuIds: ['beginner-stance-three-sets'],
    relatedKnowledgeIds: ['kb-stance-weight'],
  }),
  advice({
    id: 'stance-003',
    category: 'stance',
    title: '肩の向きが安定しない',
    problemKeywords: ['肩', '向き', '斜め'],
    adviceSummary: '足ではなく肩のラインを一つの確認項目にして、構え直しを入れましょう。',
    recommendedPracticeMenuIds: ['advanced-form-reset-eight'],
    relatedKnowledgeIds: ['kb-form-reset'],
  }),
  advice({
    id: 'stance-004',
    category: 'stance',
    title: '後半にフォームが崩れる',
    problemKeywords: ['後半', '疲れ', '崩れる'],
    adviceSummary: '疲労時は足位置とテンポが変わりやすいため、短い区切りでリセットします。',
    recommendedPracticeMenuIds: ['advanced-bull-under-fatigue'],
    relatedKnowledgeIds: ['kb-fatigue-bull'],
  }),
  advice({
    id: 'grip-001',
    category: 'grip',
    title: '強く握りすぎる',
    problemKeywords: ['握る', '力む', '強い'],
    possibleCauses: ['外したくない意識が強い', '指先で固定しすぎる'],
    adviceSummary: '握りを弱めるより、離す瞬間に同時に指が抜けるかを確認します。',
    recommendedPracticeMenuIds: ['beginner-release-short-check'],
    relatedKnowledgeIds: ['kb-grip-pressure'],
  }),
  advice({
    id: 'grip-002',
    category: 'grip',
    title: '指に引っかかる',
    problemKeywords: ['指', '引っかかる', '抜けない'],
    adviceSummary: '指先の圧が残る可能性があります。低負荷でリリースの順番を確認しましょう。',
    recommendedPracticeMenuIds: ['intermediate-release-line'],
    relatedKnowledgeIds: ['kb-release-hook'],
  }),
  advice({
    id: 'grip-003',
    category: 'grip',
    title: '毎回持ち方が変わる',
    problemKeywords: ['持ち方', 'グリップ', '変わる'],
    adviceSummary: '投げる前にバレルの触れる位置を一つだけ確認し、細かく直しすぎないようにします。',
    recommendedPracticeMenuIds: ['advanced-form-reset-eight'],
    relatedKnowledgeIds: ['kb-grip-repeat'],
  }),
  advice({
    id: 'grip-004',
    category: 'grip',
    title: '抜けが早い',
    problemKeywords: ['早い', '抜ける', '落ちる'],
    adviceSummary: '早く離れている日は握りではなく腕の出る方向も同時に見ます。',
    recommendedPracticeMenuIds: ['intermediate-release-line'],
    relatedKnowledgeIds: ['kb-release-timing'],
  }),
  advice({
    id: 'takeback-001',
    category: 'takeback',
    title: '引きすぎて遅れる',
    problemKeywords: ['テイクバック', '引きすぎ', '遅れる'],
    adviceSummary: '深さより同じ位置へ戻ることを優先し、引く速度を一定にします。',
    recommendedPracticeMenuIds: ['advanced-form-reset-eight'],
    relatedKnowledgeIds: ['kb-takeback-depth'],
  }),
  advice({
    id: 'takeback-002',
    category: 'takeback',
    title: '浅くなって飛ばない',
    problemKeywords: ['浅い', '飛ばない', '弱い'],
    adviceSummary: '無理に深くせず、腕が止まる位置を一定にしてから強さを戻します。',
    recommendedPracticeMenuIds: ['beginner-release-short-check'],
    relatedKnowledgeIds: ['kb-takeback-depth'],
  }),
  advice({
    id: 'takeback-003',
    category: 'takeback',
    title: '試合で引けなくなる',
    problemKeywords: ['試合', '引けない', '固まる'],
    adviceSummary: '緊張時は動作を小さくしてもよいので、開始位置と終了位置だけ守りましょう。',
    recommendedPracticeMenuIds: ['advanced-release-pressure-check'],
    relatedKnowledgeIds: ['kb-pressure-release'],
  }),
  advice({
    id: 'release-001',
    category: 'release',
    title: '右に抜ける',
    problemKeywords: ['右', '抜ける', '外れる'],
    adviceSummary: '離す瞬間に手が外へ逃げている可能性があります。手の残り方を確認しましょう。',
    recommendedPracticeMenuIds: ['intermediate-release-line'],
    relatedKnowledgeIds: ['kb-release-line'],
  }),
  advice({
    id: 'release-002',
    category: 'release',
    title: '低く垂れる',
    problemKeywords: ['低い', '垂れる', '落ちる'],
    adviceSummary:
      'リリースが遅いか、腕が最後まで出ていない可能性があります。強く投げずに軌道を確認します。',
    recommendedPracticeMenuIds: ['beginner-release-short-check'],
    relatedKnowledgeIds: ['kb-release-timing'],
  }),
  advice({
    id: 'release-003',
    category: 'release',
    title: '指離れがばらつく',
    problemKeywords: ['ばらつく', '離れ', '指'],
    adviceSummary: '指の順番を直そうとしすぎず、同じテンポで抜ける条件を探します。',
    recommendedPracticeMenuIds: ['intermediate-release-line'],
    relatedKnowledgeIds: ['kb-release-hook'],
  }),
  advice({
    id: 'release-004',
    category: 'release',
    title: '力むと上に抜ける',
    problemKeywords: ['上', '力む', '浮く'],
    adviceSummary: '力みで腕の出方が変わる日は、短いセットで構え直しを増やします。',
    recommendedPracticeMenuIds: ['intermediate-stance-pressure-count-up'],
    relatedKnowledgeIds: ['kb-fatigue-bull'],
  }),
  advice({
    id: 'release-005',
    category: 'release',
    title: 'プレッシャーで離せない',
    problemKeywords: ['離せない', '固まる', 'プレッシャー'],
    adviceSummary: '投げ込みで押し切らず、低負荷の確認と休む判断も選択肢にします。',
    recommendedPracticeMenuIds: ['advanced-release-pressure-check', 'intermediate-yips-low-load'],
    relatedKnowledgeIds: ['kb-yips-safe'],
  }),
  advice({
    id: 'follow-001',
    category: 'followThrough',
    title: '投げた後に手が残らない',
    problemKeywords: ['フォロー', '残らない', '手'],
    adviceSummary: '当てに行く意識が強いと手が止まりやすいので、投げ終わりの形を確認します。',
    recommendedPracticeMenuIds: ['advanced-form-reset-eight'],
    relatedKnowledgeIds: ['kb-follow-through'],
  }),
  advice({
    id: 'follow-002',
    category: 'followThrough',
    title: '肘が外へ流れる',
    problemKeywords: ['肘', '外', '流れる'],
    adviceSummary: '肘を固定しすぎず、狙い方向へ自然に出るかを見ます。',
    recommendedPracticeMenuIds: ['intermediate-release-line'],
    relatedKnowledgeIds: ['kb-release-line'],
  }),
  advice({
    id: 'follow-003',
    category: 'followThrough',
    title: '3投目だけ崩れる',
    problemKeywords: ['3投目', '最後', '崩れる'],
    adviceSummary: '結果を急ぐ可能性があります。3投目だけ一呼吸置くルーティンを入れます。',
    recommendedPracticeMenuIds: ['beginner-routine-one-breath'],
    relatedKnowledgeIds: ['kb-routine-one-breath'],
  }),
  advice({
    id: 'aim-001',
    category: 'aiming',
    title: 'ブルに入らない',
    problemKeywords: ['ブル', '入らない', '合わない'],
    adviceSummary: '狙いを変え続けず、外れ方の偏りを先に記録します。',
    recommendedPracticeMenuIds: ['beginner-bull-count-up-12'],
    relatedKnowledgeIds: ['kb-countup-bull'],
  }),
  advice({
    id: 'aim-002',
    category: 'aiming',
    title: 'クリケットの番号が合わない',
    problemKeywords: ['クリケット', '番号', '合わない'],
    adviceSummary: '番号ごとの差を分けて記録し、最低ナンバーを次のテーマにします。',
    recommendedPracticeMenuIds: ['intermediate-cricket-count-up-map'],
    relatedKnowledgeIds: ['kb-cricket-number-map'],
  }),
  advice({
    id: 'aim-003',
    category: 'aiming',
    title: '狙いすぎて固い',
    problemKeywords: ['狙いすぎ', '固い', '慎重'],
    adviceSummary: '狙いの細かさより、構えてから投げるまでの時間を一定にしましょう。',
    recommendedPracticeMenuIds: ['beginner-routine-one-breath'],
    relatedKnowledgeIds: ['kb-routine-one-breath'],
  }),
  advice({
    id: 'rhythm-001',
    category: 'rhythm',
    title: 'テンポが速くなる',
    problemKeywords: ['速い', 'テンポ', '急ぐ'],
    adviceSummary: '高得点後やミス後に急ぎやすいので、ラウンド単位で一呼吸入れます。',
    recommendedPracticeMenuIds: ['beginner-routine-one-breath'],
    relatedKnowledgeIds: ['kb-rhythm-control'],
  }),
  advice({
    id: 'rhythm-002',
    category: 'rhythm',
    title: '考えすぎて止まる',
    problemKeywords: ['止まる', '考えすぎ', '迷う'],
    adviceSummary: '確認項目を1つだけにして、残りの修正は記録後に回します。',
    recommendedPracticeMenuIds: ['intermediate-mental-three-leg'],
    relatedKnowledgeIds: ['kb-mental-reset'],
  }),
  advice({
    id: 'rhythm-003',
    category: 'rhythm',
    title: 'ラウンドごとにリズムが変わる',
    problemKeywords: ['リズム', '変わる', 'ラウンド'],
    adviceSummary: '投げる前の動作を短く固定し、点数でテンポを変えないようにします。',
    recommendedPracticeMenuIds: ['intermediate-stance-pressure-count-up'],
    relatedKnowledgeIds: ['kb-rhythm-control'],
  }),
  advice({
    id: 'mental-001',
    category: 'mental',
    title: '試合で腕が固まる',
    problemKeywords: ['試合', '固まる', '緊張'],
    adviceSummary: '結果ではなく、開始前の一呼吸と確認項目だけに注意を戻します。',
    recommendedPracticeMenuIds: ['intermediate-mental-three-leg'],
    relatedKnowledgeIds: ['kb-pressure-release'],
  }),
  advice({
    id: 'mental-002',
    category: 'mental',
    title: 'ミスを引きずる',
    problemKeywords: ['引きずる', 'ミス', '焦る'],
    adviceSummary: 'ミス後の1投目を別メニューとして扱い、立て直しを評価します。',
    recommendedPracticeMenuIds: ['advanced-01-pressure-set'],
    relatedKnowledgeIds: ['kb-mental-reset'],
  }),
  advice({
    id: 'mental-003',
    category: 'mental',
    title: '上がりで焦る',
    problemKeywords: ['上がり', '焦る', '01'],
    adviceSummary: '第一候補だけでなく保険ルートも決めて、外した後の選択を準備します。',
    recommendedPracticeMenuIds: ['advanced-dartslive-01-arrange'],
    relatedKnowledgeIds: ['kb-zeroone-route'],
  }),
  advice({
    id: 'yips-001',
    category: 'yips',
    title: '投げ出しが怖い',
    problemKeywords: ['怖い', '投げられない', '不安'],
    adviceSummary: '無理に投げ込まず、素振りや近い意識の低負荷確認から始めます。',
    recommendedPracticeMenuIds: ['intermediate-yips-low-load'],
    relatedKnowledgeIds: ['kb-yips-safe'],
    cautionText: '違和感が強い場合は休養や専門家相談も選択肢です。無理な投げ込みは避けてください。',
    severity: 'serious',
  }),
  advice({
    id: 'yips-002',
    category: 'yips',
    title: '指が離れない感じがする',
    problemKeywords: ['離れない', '指', '固まる'],
    adviceSummary: '成功させるより、違和感が出る条件を安全に言語化します。',
    recommendedPracticeMenuIds: ['intermediate-yips-low-load'],
    relatedKnowledgeIds: ['kb-yips-safe'],
    cautionText: '医療的な診断ではありません。強い症状が続く場合は休む判断も大切です。',
    severity: 'serious',
  }),
  advice({
    id: 'yips-003',
    category: 'yips',
    title: '試合だけ投げにくい',
    problemKeywords: ['試合', '投げにくい', '本番'],
    adviceSummary: '本番を再現しすぎず、短いルーティンで安心して始められる条件を作ります。',
    recommendedPracticeMenuIds: ['advanced-release-pressure-check'],
    relatedKnowledgeIds: ['kb-pressure-release'],
    cautionText: '不安を強める練習は避け、負荷を下げる選択を残しましょう。',
  }),
  advice({
    id: 'yips-004',
    category: 'yips',
    title: '投げ込みで悪化する',
    problemKeywords: ['悪化', '投げ込み', 'つらい'],
    adviceSummary: '投数を増やすほど悪化する日は中止基準を先に決めます。',
    recommendedPracticeMenuIds: ['intermediate-yips-low-load'],
    relatedKnowledgeIds: ['kb-yips-safe'],
    cautionText: '休養や専門家相談を含め、無理をしない選択を優先してください。',
    severity: 'serious',
  }),
  advice({
    id: 'yips-005',
    category: 'yips',
    title: '力みが抜けない',
    problemKeywords: ['力み', '抜けない', '怖い'],
    adviceSummary: '力みをゼロにしようとせず、弱い負荷で終えられる成功条件を探します。',
    recommendedPracticeMenuIds: ['beginner-routine-one-breath', 'intermediate-yips-low-load'],
    relatedKnowledgeIds: ['kb-yips-safe'],
    cautionText: '「必ず治す」より、今日は悪化させない練習を選びましょう。',
  }),
  advice({
    id: 'plan-001',
    category: 'practicePlan',
    title: '何を練習すればよいか分からない',
    problemKeywords: ['分からない', '練習方法', 'メニュー'],
    adviceSummary: '悩みを1つに絞り、短時間メニューを週3回から始めます。',
    recommendedPracticeMenuIds: ['beginner-bull-count-up-12', 'beginner-routine-one-breath'],
    relatedKnowledgeIds: ['kb-practice-weekly'],
  }),
  advice({
    id: 'plan-002',
    category: 'practicePlan',
    title: '練習しても伸びない',
    problemKeywords: ['伸びない', '停滞', '変わらない'],
    adviceSummary: 'スコアだけでなく、ブル数やメモを残して次の練習に変換します。',
    recommendedPracticeMenuIds: ['intermediate-cricket-count-up-map'],
    relatedKnowledgeIds: ['kb-practice-log'],
  }),
  advice({
    id: 'plan-003',
    category: 'practicePlan',
    title: '試合前に何をするか迷う',
    problemKeywords: ['試合前', '迷う', '準備'],
    adviceSummary: '新しい修正は入れず、短い確認メニューで再現性だけを見ます。',
    recommendedPracticeMenuIds: ['advanced-form-reset-eight'],
    relatedKnowledgeIds: ['kb-form-reset'],
  }),
];
