import type { KnowledgeArticle } from '../types';

const sourceNotes = [
  'Generalized soft darts coaching knowledge. No direct quotation.',
  'Original summary for app prototype. Source attribution to be added later.',
];

export const knowledgeBase: KnowledgeArticle[] = [
  {
    id: 'kb-stance-setup',
    category: 'stance',
    title: 'スタンスを固定する考え方',
    summary: '足位置を毎回同じに戻すための基本チェック。',
    body: 'スタンスは細かく変え続けるより、戻る場所を決めることが大切です。構える前に足幅、つま先、肩の向きを一つずつ確認し、外れた結果だけで立ち方を変えすぎないようにします。',
    tags: ['スタンス', 'フォーム確認'],
    relatedPracticeMenuIds: ['beginner-stance-three-sets'],
    relatedAdviceIds: ['stance-001'],
    sourceNotes,
  },
  {
    id: 'kb-stance-weight',
    category: 'stance',
    title: '重心位置のセルフチェック',
    summary: '前後の揺れを減らすための足裏確認。',
    body: '重心が大きく動くと、リリースや狙いの修正が難しくなります。投げる前に足裏のどこへ圧があるかを確認し、投げ終わりに大きく流れていないかを見ます。',
    tags: ['重心', 'スタンス'],
    relatedPracticeMenuIds: ['beginner-stance-three-sets'],
    relatedAdviceIds: ['stance-002'],
    sourceNotes,
  },
  {
    id: 'kb-grip-pressure',
    category: 'grip',
    title: '握り込みを減らす観察ポイント',
    summary: '強く握る癖を感覚ではなく観察で見つける。',
    body: '握りを弱めようとしすぎると不安定になることがあります。離す瞬間に指が残っていないか、投げ終わりに手が固まっていないかを見ると、修正点を小さくできます。',
    tags: ['グリップ', '力み'],
    relatedPracticeMenuIds: ['beginner-release-short-check'],
    relatedAdviceIds: ['grip-001'],
    sourceNotes,
  },
  {
    id: 'kb-grip-repeat',
    category: 'grip',
    title: '毎回同じ持ち方に戻す',
    summary: '触れる位置を一つだけ確認する方法。',
    body: 'グリップの再現性は、全ての指を細かく直すより、基準になる触点を一つ決めるほうが安定しやすいです。違和感がある日も修正項目を増やしすぎないようにします。',
    tags: ['グリップ', '再現性'],
    relatedPracticeMenuIds: ['advanced-form-reset-eight'],
    relatedAdviceIds: ['grip-003'],
    sourceNotes,
  },
  {
    id: 'kb-takeback-depth',
    category: 'takeback',
    title: 'テイクバックの深さと再現性',
    summary: '深さを固定するより戻る位置を一定にする。',
    body: 'テイクバックは深ければ良いわけではありません。引く速度と戻る位置が毎回近いかを確認し、試合で小さくなっても再現できる範囲に収めます。',
    tags: ['テイクバック', 'フォーム確認'],
    relatedPracticeMenuIds: ['advanced-form-reset-eight'],
    relatedAdviceIds: ['takeback-001', 'takeback-002'],
    sourceNotes,
  },
  {
    id: 'kb-release-line',
    category: 'release',
    title: 'リリースラインの見方',
    summary: '手が狙い方向へ残るかを確認する。',
    body: '左右のズレが続くときは、狙いではなく手の残り方を見ると原因を分けやすくなります。投げ終わりに手が外へ逃げるか、内側へ巻くかを短くメモします。',
    tags: ['リリース', '左右ブレ'],
    relatedPracticeMenuIds: ['intermediate-release-line'],
    relatedAdviceIds: ['release-001', 'follow-002'],
    sourceNotes,
  },
  {
    id: 'kb-release-hook',
    category: 'release',
    title: '指に引っかかる時の分け方',
    summary: 'グリップとリリースを同時に見すぎない。',
    body: '指に引っかかる日は握りだけを疑うと修正が増えます。腕の出る方向、指が離れる順番、力みの有無を分けて、低負荷で確認します。',
    tags: ['リリース', 'グリップ'],
    relatedPracticeMenuIds: ['intermediate-release-line'],
    relatedAdviceIds: ['grip-002', 'release-003'],
    sourceNotes,
  },
  {
    id: 'kb-release-timing',
    category: 'release',
    title: '早い抜けと遅い抜け',
    summary: '上下のズレからタイミングを推測する。',
    body: '低く垂れる、上に抜けるなどの上下ズレは、リリースタイミングの手がかりになります。強く投げて直す前に、同じテンポで再現するかを確認します。',
    tags: ['リリース', '上下ブレ'],
    relatedPracticeMenuIds: ['beginner-release-short-check'],
    relatedAdviceIds: ['release-002', 'grip-004'],
    sourceNotes,
  },
  {
    id: 'kb-follow-through',
    category: 'release',
    title: 'フォロースルーを確認する理由',
    summary: '投げ終わりの形から力みを見つける。',
    body: 'フォロースルーは形を作るためだけでなく、投げる途中で力んだかを知る材料です。手が止まる、肘が流れるなどを一つだけ観察します。',
    tags: ['フォロースルー', 'フォーム確認'],
    relatedPracticeMenuIds: ['advanced-form-reset-eight'],
    relatedAdviceIds: ['follow-001'],
    sourceNotes,
  },
  {
    id: 'kb-countup-bull',
    category: 'countUp',
    title: 'COUNT-UPでブル率を見る',
    summary: 'スコアだけでなくブル数と外れ方を残す。',
    body: 'COUNT-UPは点数だけを見ると練習テーマがぼやけます。ブル数、外れた方向、力みの有無を残すと、次の練習へつなげやすくなります。',
    tags: ['COUNT-UP', 'ブル練習'],
    relatedPracticeMenuIds: ['beginner-bull-count-up-12', 'advanced-bull-under-fatigue'],
    relatedAdviceIds: ['aim-001'],
    sourceNotes,
  },
  {
    id: 'kb-cricket-number-map',
    category: 'cricket',
    title: 'クリケットの弱点番号を見つける',
    summary: '15〜20を分けて記録する考え方。',
    body: 'クリケットが苦手なときは、全体の印象ではなく番号ごとのマーク数を分けます。最低番号を次回テーマにすると練習が具体化します。',
    tags: ['CRICKET', 'ナンバー練習'],
    relatedPracticeMenuIds: [
      'intermediate-cricket-count-up-map',
      'intermediate-phoenix-cricket-15-20',
    ],
    relatedAdviceIds: ['aim-002'],
    sourceNotes,
  },
  {
    id: 'kb-zeroone-route',
    category: 'zeroOne',
    title: '01で迷いを減らす',
    summary: '第一候補と保険ルートを持つ。',
    body: '01では上がれるかだけでなく、外した後に残る点数も重要です。第一候補と保険を決めてから投げると、焦りにくくなります。',
    tags: ['01', 'アレンジ'],
    relatedPracticeMenuIds: ['beginner-01-finish-note', 'advanced-dartslive-01-arrange'],
    relatedAdviceIds: ['mental-003'],
    sourceNotes,
  },
  {
    id: 'kb-routine-one-breath',
    category: 'routine',
    title: '一呼吸ルーティン',
    summary: '確認項目を一つに絞る。',
    body: 'ルーティンは長くするほど試合中に崩れやすくなります。一呼吸、足位置、手の残り方など、今日の確認項目を一つに絞ります。',
    tags: ['ルーティン', 'メンタル'],
    relatedPracticeMenuIds: ['beginner-routine-one-breath'],
    relatedAdviceIds: ['stance-001', 'follow-003', 'aim-003'],
    sourceNotes,
  },
  {
    id: 'kb-rhythm-control',
    category: 'routine',
    title: 'テンポが変わる場面を見つける',
    summary: '高得点後とミス後に注意する。',
    body: 'テンポは良い時にも悪い時にも変わります。高得点後に急ぐ、ミス後に長く止まるなど、変化する場面を記録します。',
    tags: ['リズム', 'ルーティン'],
    relatedPracticeMenuIds: [
      'beginner-routine-one-breath',
      'intermediate-stance-pressure-count-up',
    ],
    relatedAdviceIds: ['rhythm-001', 'rhythm-003'],
    sourceNotes,
  },
  {
    id: 'kb-mental-reset',
    category: 'mental',
    title: 'ミス後のリセット',
    summary: '次の1投を別の練習として扱う。',
    body: 'ミスを取り返そうとすると判断が速くなりすぎます。ミス後の1投だけを丁寧にする、という小さな目標に切り替えます。',
    tags: ['メンタル', 'リセット'],
    relatedPracticeMenuIds: ['intermediate-mental-three-leg', 'advanced-01-pressure-set'],
    relatedAdviceIds: ['mental-002', 'rhythm-002'],
    sourceNotes,
  },
  {
    id: 'kb-pressure-release',
    category: 'mental',
    title: 'プレッシャー時のリリース',
    summary: '緊張時は動作が小さくなりやすい。',
    body: '試合や上がり場面では、テイクバックやリリースが普段より小さくなることがあります。大きく直すより、開始位置と終了位置だけを確認します。',
    tags: ['プレッシャー', 'リリース'],
    relatedPracticeMenuIds: ['advanced-release-pressure-check', 'intermediate-mental-three-leg'],
    relatedAdviceIds: ['takeback-003', 'mental-001', 'yips-003'],
    sourceNotes,
  },
  {
    id: 'kb-yips-safe',
    category: 'yips',
    title: 'イップス気味の日の安全な練習',
    summary: '無理な投げ込みを避ける考え方。',
    body: '投げ出しが怖い、指が離れない感覚が強い日は、成功数を増やすより悪化させないことを優先します。休養や専門家相談も選択肢として残します。',
    tags: ['イップス', '安全'],
    relatedPracticeMenuIds: ['intermediate-yips-low-load'],
    relatedAdviceIds: ['yips-001', 'yips-002', 'yips-004', 'yips-005'],
    sourceNotes,
  },
  {
    id: 'kb-practice-weekly',
    category: 'practicePlan',
    title: '週3回の短時間練習',
    summary: '続けやすい練習量から始める。',
    body: '練習量が安定しない時は、長時間より短時間を週3回続けるほうが傾向を見やすくなります。記録項目も少なくします。',
    tags: ['練習計画', '継続'],
    relatedPracticeMenuIds: ['beginner-bull-count-up-12', 'beginner-routine-one-breath'],
    relatedAdviceIds: ['plan-001'],
    sourceNotes,
  },
  {
    id: 'kb-practice-log',
    category: 'practicePlan',
    title: '記録を次の練習に変える',
    summary: 'スコア以外の項目を残す理由。',
    body: 'スコアだけでは原因が見えにくいため、ブル数、マーク数、調子、メモを一緒に残します。次回の練習テーマを一つ決める材料になります。',
    tags: ['記録', '分析'],
    relatedPracticeMenuIds: ['intermediate-cricket-count-up-map'],
    relatedAdviceIds: ['plan-002'],
    sourceNotes,
  },
  {
    id: 'kb-form-reset',
    category: 'practicePlan',
    title: '試合前のフォーム確認',
    summary: '新しい修正を入れない準備。',
    body: '試合前は大きな修正を増やさず、立ち位置、手の残り方、テンポのどれか一つだけを確認します。短時間で終えることも大切です。',
    tags: ['フォーム確認', '試合前'],
    relatedPracticeMenuIds: ['advanced-form-reset-eight'],
    relatedAdviceIds: ['plan-003', 'stance-003'],
    sourceNotes,
  },
  {
    id: 'kb-fatigue-bull',
    category: 'countUp',
    title: '疲労下でブル率を見る',
    summary: '後半の落ち幅を確認する。',
    body: '疲れてくると腕だけで投げやすくなります。前半と後半のブル数を分けて残すと、フォーム維持の課題が見えます。',
    tags: ['ブル練習', '疲労'],
    relatedPracticeMenuIds: ['advanced-bull-under-fatigue'],
    relatedAdviceIds: ['stance-004', 'release-004'],
    sourceNotes,
  },
];

export function getKnowledgeArticleById(id: string) {
  return knowledgeBase.find((article) => article.id === id) ?? null;
}

export function getKnowledgeArticlesByCategory(category: string) {
  return knowledgeBase.filter((article) => article.category === category);
}

export function getKnowledgeArticlesByPracticeMenuId(practiceMenuId: string) {
  return knowledgeBase.filter((article) => article.relatedPracticeMenuIds.includes(practiceMenuId));
}

export function getKnowledgeArticlesByAdviceIds(adviceIds: string[]) {
  return knowledgeBase.filter((article) =>
    article.relatedAdviceIds.some((adviceId) => adviceIds.includes(adviceId)),
  );
}
