import type { DartMachine, PracticeGame, PracticeMenu, SkillLevelId } from '../types';

type MenuSeed = {
  id: string;
  title: string;
  level: SkillLevelId;
  machineTypes?: DartMachine[];
  gameTypes: PracticeGame[];
  targetProblems: string[];
  durationMinutes: number;
  purpose: string;
  steps: string[];
  recordItems: string[];
  evaluationPoints: string[];
  adviceText: string;
  difficulty: 1 | 2 | 3 | 4 | 5;
  tags: string[];
  sourceNotes?: string[];
};

const bothMachines: DartMachine[] = ['DARTSLIVE', 'PHOENIX', 'BOTH'];

function menu(seed: MenuSeed): PracticeMenu {
  return {
    machineTypes: seed.machineTypes ?? bothMachines,
    ...seed,
  };
}

export const practiceMenus: PracticeMenu[] = [
  menu({
    id: 'beginner-bull-count-up-12',
    title: 'ブル位置確認 COUNT-UP',
    level: 'beginner',
    gameTypes: ['COUNT-UP'],
    targetProblems: ['ブル率が低い', '練習方法が分からない'],
    durationMinutes: 12,
    purpose: '力まず同じリズムでブル周辺へ集める。',
    steps: ['1ラウンドごとに深呼吸する', '狙いはブルだけに絞る', '外れ方を左右上下でメモする'],
    recordItems: ['スコア', 'ブル数', '外れ方'],
    evaluationPoints: ['ブル数が前回より増えたか', '同じ外れ方が続いたか'],
    adviceText: 'スコアよりも外れ方の偏りを見ます。右に抜ける日はリリース確認へ寄せましょう。',
    difficulty: 1,
    tags: ['ブル練習', 'COUNT-UP', '短時間'],
  }),
  menu({
    id: 'beginner-stance-three-sets',
    title: 'スタンス固定 3セット',
    level: 'beginner',
    gameTypes: ['OTHER'],
    targetProblems: ['フォームが安定しない', '練習方法が分からない'],
    durationMinutes: 10,
    purpose: '毎投同じ立ち位置に戻る感覚を作る。',
    steps: ['足位置を決める', '3投ごとに一度構え直す', '肩の向きだけ確認して投げる'],
    recordItems: ['違和感', '左右ブレ', 'メモ'],
    evaluationPoints: ['構え直しても狙いが変わらないか', '力みが増えていないか'],
    adviceText: '足元の再現性が低いと修正点が増えます。まずは立ち直しを習慣にしましょう。',
    difficulty: 1,
    tags: ['スタンス安定', 'フォーム確認'],
  }),
  menu({
    id: 'beginner-release-short-check',
    title: '近距離リリース確認',
    level: 'beginner',
    gameTypes: ['OTHER'],
    targetProblems: ['リリースが抜ける', 'フォームが安定しない', 'イップス気味'],
    durationMinutes: 8,
    purpose: '抜けや引っかかりを低負荷で確認する。',
    steps: [
      '近い距離を想定して素振りする',
      '指離れのタイミングを言語化する',
      '違和感が出たら投数を減らす',
    ],
    recordItems: ['抜け感', '指の引っかかり', 'メモ'],
    evaluationPoints: ['強く握らず投げられたか', '違和感を説明できたか'],
    adviceText: '不安が強い日は投げ込みより確認量を減らすことを優先します。',
    difficulty: 1,
    tags: ['リリース安定', 'イップス対策', 'フォーム確認'],
  }),
  menu({
    id: 'beginner-01-finish-note',
    title: '01上がり目メモ練習',
    level: 'beginner',
    gameTypes: ['01'],
    targetProblems: ['01が苦手', '練習方法が分からない'],
    durationMinutes: 15,
    purpose: '残り点から次の狙いを決める癖を作る。',
    steps: ['残り点を声に出す', '無理な上がりを狙わず整える', '迷った点数をメモする'],
    recordItems: ['スコア', '迷った残り点', '調子'],
    evaluationPoints: ['狙いを決める時間が短くなったか', '無理な選択が減ったか'],
    adviceText: '上がれないことより、迷いを減らすことを評価しましょう。',
    difficulty: 2,
    tags: ['01系', 'メンタル・ルーティン'],
  }),
  menu({
    id: 'beginner-number-20-19-18',
    title: '20・19・18 基礎ナンバー',
    level: 'beginner',
    gameTypes: ['CRICKET', 'OTHER'],
    targetProblems: ['クリケットが苦手', '練習方法が分からない'],
    durationMinutes: 12,
    purpose: '主要ナンバーの高さと左右感覚を覚える。',
    steps: ['20を3ラウンド', '19を3ラウンド', '18を3ラウンド', '当たりやすい番号を確認する'],
    recordItems: ['マーク数', '得意番号', '苦手番号'],
    evaluationPoints: ['番号ごとの差が見えたか', '狙いを切り替えられたか'],
    adviceText: '苦手番号だけを責めず、得意番号も確認すると次の練習が選びやすくなります。',
    difficulty: 2,
    tags: ['ナンバー練習', 'CRICKET系'],
  }),
  menu({
    id: 'beginner-routine-one-breath',
    title: '一呼吸ルーティン',
    level: 'beginner',
    gameTypes: ['COUNT-UP', '01', 'CRICKET'],
    targetProblems: ['フォームが安定しない', 'イップス気味'],
    durationMinutes: 8,
    purpose: '投げる前の確認項目を1つに絞る。',
    steps: ['構える前に一呼吸置く', '確認項目を1つだけ決める', '結果を見すぎず次投へ移る'],
    recordItems: ['確認項目', '力み', '調子'],
    evaluationPoints: ['毎投同じ入り方ができたか', '結果で急がなかったか'],
    adviceText: 'ルーティンは長くしすぎず、試合中でも再現できる短さにします。',
    difficulty: 1,
    tags: ['メンタル・ルーティン', 'フォーム確認'],
  }),
  menu({
    id: 'beginner-phoenix-count-up-note',
    title: 'PHOENIX COUNT-UP メモ練習',
    level: 'beginner',
    machineTypes: ['PHOENIX', 'BOTH'],
    gameTypes: ['COUNT-UP'],
    targetProblems: ['ブル率が低い', '練習方法が分からない'],
    durationMinutes: 15,
    purpose: 'COUNT-UPの結果を感覚メモとセットで残す。',
    steps: ['1ゲーム投げる', 'ブル数を書く', '力みと抜け感を一言で残す'],
    recordItems: ['スコア', 'ブル数', '感覚メモ'],
    evaluationPoints: ['数字と感覚が結びついたか', '次回の確認項目が決まったか'],
    adviceText: '機種名は記録ラベルとして扱い、公式画面の模写はしません。',
    difficulty: 1,
    tags: ['COUNT-UP系', 'ブル練習'],
  }),
  menu({
    id: 'beginner-dartslive-01-safe-route',
    title: 'DARTSLIVE 01安全ルート',
    level: 'beginner',
    machineTypes: ['DARTSLIVE', 'BOTH'],
    gameTypes: ['01'],
    targetProblems: ['01が苦手'],
    durationMinutes: 15,
    purpose: '無理に上がらず、次ラウンドを楽にする選択を練習する。',
    steps: ['残り点を確認する', '安全に減らす狙いを選ぶ', '迷った場面を保存する'],
    recordItems: ['スコア', '迷った残り点', 'メモ'],
    evaluationPoints: ['大きなミス後に立て直せたか', '狙いを説明できるか'],
    adviceText: '初級では正解を増やすより、避けたい選択を減らすほうが安定します。',
    difficulty: 2,
    tags: ['01系', 'メンタル・ルーティン'],
  }),
  menu({
    id: 'intermediate-cricket-19-cover',
    title: '19カバードリル',
    level: 'intermediate',
    gameTypes: ['CRICKET'],
    targetProblems: ['クリケットが苦手'],
    durationMinutes: 12,
    purpose: '20が詰まった後のカバー精度を上げる。',
    steps: ['20を狙う', '外れが続いたら19へ切り替える', '切り替え判断をメモする'],
    recordItems: ['19マーク数', '20ミス数', '判断メモ'],
    evaluationPoints: ['切り替えが遅れていないか', '19で立て直せたか'],
    adviceText: '同じ番号に固執せず、次の有利な選択へ移る練習です。',
    difficulty: 3,
    tags: ['CRICKET系', 'ナンバー練習'],
  }),
  menu({
    id: 'intermediate-bull-01-switch',
    title: 'Bull安定 + 01切り替え',
    level: 'intermediate',
    gameTypes: ['COUNT-UP', '01'],
    targetProblems: ['ブル率が低い', '01が苦手'],
    durationMinutes: 18,
    purpose: 'ブル狙いから01の実戦判断へつなげる。',
    steps: ['COUNT-UPを短く投げる', 'ブル数を確認する', '01で同じリズムを保つ'],
    recordItems: ['スコア', 'ブル数', '01で崩れた場面'],
    evaluationPoints: ['ゲーム変更後もテンポが変わらないか', 'ブル狙いが雑にならないか'],
    adviceText: '練習ゲームを切り替えた直後の崩れを見つけます。',
    difficulty: 3,
    tags: ['ブル練習', '01系', 'COUNT-UP系'],
  }),
  menu({
    id: 'intermediate-cricket-count-up-map',
    title: 'Cricket Count-Up 弱点マップ',
    level: 'intermediate',
    gameTypes: ['CRICKET'],
    targetProblems: ['クリケットが苦手'],
    durationMinutes: 15,
    purpose: '得意ナンバーと弱点ナンバーを分ける。',
    steps: ['各ナンバーを順に狙う', 'マーク数を残す', '最低マークの番号を次回テーマにする'],
    recordItems: ['総マーク数', '最低ナンバー', '最高ナンバー'],
    evaluationPoints: ['弱点番号が明確になったか', '得意番号に逃げすぎていないか'],
    adviceText: '弱点を1つだけ選ぶと、次の練習が散らかりません。',
    difficulty: 3,
    tags: ['CRICKET系', 'ナンバー練習'],
  }),
  menu({
    id: 'intermediate-release-line',
    title: 'リリースライン再現',
    level: 'intermediate',
    gameTypes: ['OTHER', 'COUNT-UP'],
    targetProblems: ['リリースが抜ける', 'フォームが安定しない'],
    durationMinutes: 12,
    purpose: '腕の出る方向と指離れをそろえる。',
    steps: ['素振りでラインを確認する', '1投ごとに手の残り方を見る', '抜けた投げ方をメモする'],
    recordItems: ['抜け感', '左右ブレ', 'メモ'],
    evaluationPoints: ['同じ方向へ手が残るか', '抜けた投げ方を説明できるか'],
    adviceText: '狙いを増やさず、リリースの再現だけを評価します。',
    difficulty: 3,
    tags: ['リリース安定', 'フォーム確認'],
  }),
  menu({
    id: 'intermediate-stance-pressure-count-up',
    title: 'スタンス維持 COUNT-UP',
    level: 'intermediate',
    gameTypes: ['COUNT-UP'],
    targetProblems: ['フォームが安定しない', 'ブル率が低い'],
    durationMinutes: 16,
    purpose: 'スコアを意識しても立ち位置を崩さない。',
    steps: ['1ゲーム投げる', '高得点後も足位置を確認する', '低得点後も構え直す'],
    recordItems: ['スコア', 'ブル数', '崩れたラウンド'],
    evaluationPoints: ['点数で急がなかったか', '足位置が変わっていないか'],
    adviceText: '結果が良い時ほどテンポが速くなりやすいので、構え直しを固定します。',
    difficulty: 3,
    tags: ['スタンス安定', 'COUNT-UP系', 'ブル練習'],
  }),
  menu({
    id: 'intermediate-mental-three-leg',
    title: '3レッグ集中ルーティン',
    level: 'intermediate',
    gameTypes: ['01'],
    targetProblems: ['01が苦手', 'イップス気味'],
    durationMinutes: 20,
    purpose: '複数レッグで集中の入り直しを練習する。',
    steps: ['3レッグ分のテーマを決める', '各レッグ開始前に一呼吸置く', '崩れた場面だけメモする'],
    recordItems: ['スコア', '崩れた場面', 'ルーティン実施'],
    evaluationPoints: ['次レッグへ引きずらなかったか', '確認項目を守れたか'],
    adviceText: '失敗後の1投目を丁寧にすることを評価しましょう。',
    difficulty: 3,
    tags: ['01系', 'メンタル・ルーティン'],
  }),
  menu({
    id: 'intermediate-yips-low-load',
    title: '低負荷スロー再開セット',
    level: 'intermediate',
    gameTypes: ['OTHER'],
    targetProblems: ['イップス気味', 'リリースが抜ける'],
    durationMinutes: 10,
    purpose: '投げ込みを避けて安心して動作を戻す。',
    steps: ['素振りを多めにする', '近い意識で軽く投げる', '違和感が強い日は終了する'],
    recordItems: ['不安度', '抜け感', '中止判断'],
    evaluationPoints: ['無理に投数を増やしていないか', '安全に終えられたか'],
    adviceText: '医療判断ではなく練習上のセルフチェックとして扱います。',
    difficulty: 2,
    tags: ['イップス対策', 'リリース安定'],
  }),
  menu({
    id: 'intermediate-phoenix-cricket-15-20',
    title: 'PHOENIX 15〜20ローテーション',
    level: 'intermediate',
    machineTypes: ['PHOENIX', 'BOTH'],
    gameTypes: ['CRICKET'],
    targetProblems: ['クリケットが苦手'],
    durationMinutes: 18,
    purpose: '15〜20の切り替え精度を上げる。',
    steps: ['20から15まで順に狙う', '各番号のマーク数を残す', '最低番号をもう一度狙う'],
    recordItems: ['各番号マーク数', '最低番号', '集中度'],
    evaluationPoints: ['切り替えで構えが変わっていないか', '苦手番号を避けていないか'],
    adviceText: '番号ごとの高さと横ズレを分けて見ます。',
    difficulty: 3,
    tags: ['CRICKET系', 'ナンバー練習'],
  }),
  menu({
    id: 'advanced-01-pressure-set',
    title: '01プレッシャーセット',
    level: 'advanced',
    gameTypes: ['01'],
    targetProblems: ['01が苦手', 'フォームが安定しない'],
    durationMinutes: 25,
    purpose: '高い集中状態でアレンジと決定力を確認する。',
    steps: ['目標レッグ数を決める', '上がり目までの選択を記録する', '外した後の次投を評価する'],
    recordItems: ['スコア', '上がり率', 'ミス傾向'],
    evaluationPoints: ['決め切る場面で急いでいないか', '外した後の判断が崩れていないか'],
    adviceText: '上がれたかだけでなく、外した後の選択を見ます。',
    difficulty: 5,
    tags: ['01系', 'メンタル・ルーティン'],
  }),
  menu({
    id: 'advanced-cricket-switch-judgement',
    title: 'Cricket切り替え判断',
    level: 'advanced',
    gameTypes: ['CRICKET'],
    targetProblems: ['クリケットが苦手'],
    durationMinutes: 22,
    purpose: '攻める場面と閉める場面の判断速度を上げる。',
    steps: ['状況を想定して番号を選ぶ', '切り替え理由を短くメモする', '判断が遅れた場面を残す'],
    recordItems: ['マーク数', '判断メモ', '遅れた場面'],
    evaluationPoints: ['目的のない切り替えがないか', '守る判断が遅れていないか'],
    adviceText: '狙いの正確さだけでなく、選択の理由を評価します。',
    difficulty: 5,
    tags: ['CRICKET系', 'ナンバー練習'],
  }),
  menu({
    id: 'advanced-form-reset-eight',
    title: 'フォーム再現性 8分リセット',
    level: 'advanced',
    gameTypes: ['OTHER'],
    targetProblems: ['フォームが安定しない', 'リリースが抜ける'],
    durationMinutes: 8,
    purpose: '試合前に崩れやすい動作を短時間で整える。',
    steps: ['スタンスを確認する', 'リリースの手残りを見る', '違和感が小さい確認だけ続ける'],
    recordItems: ['違和感', '修正ポイント', '調子'],
    evaluationPoints: ['短時間で確認項目を絞れたか', '修正しすぎていないか'],
    adviceText: '上級者ほど修正点を増やしがちなので、1テーマだけにします。',
    difficulty: 4,
    tags: ['フォーム確認', 'スタンス安定', 'リリース安定'],
  }),
  menu({
    id: 'advanced-bull-under-fatigue',
    title: '疲労下Bullキープ',
    level: 'advanced',
    gameTypes: ['COUNT-UP'],
    targetProblems: ['ブル率が低い', 'フォームが安定しない'],
    durationMinutes: 20,
    purpose: '疲れてきた後半でもブル狙いの質を保つ。',
    steps: ['前半は通常テンポで投げる', '後半は構え直しを増やす', '後半ブル数を比較する'],
    recordItems: ['前半ブル数', '後半ブル数', '力み'],
    evaluationPoints: ['後半に腕だけで投げていないか', '構え直しで戻せたか'],
    adviceText: '後半の落ち幅が大きい日は短時間メニューへ戻しましょう。',
    difficulty: 4,
    tags: ['ブル練習', 'COUNT-UP系', 'スタンス安定'],
  }),
  menu({
    id: 'advanced-number-pressure-20-19',
    title: '20/19 高負荷ナンバー',
    level: 'advanced',
    gameTypes: ['CRICKET', 'OTHER'],
    targetProblems: ['クリケットが苦手'],
    durationMinutes: 18,
    purpose: '試合で使う主要ナンバーの決定力を上げる。',
    steps: ['20を重点的に狙う', '外れが続いたら19へ切り替える', '戻す判断を記録する'],
    recordItems: ['20マーク数', '19マーク数', '切り替え判断'],
    evaluationPoints: ['切り替えが感情的になっていないか', '戻す判断が明確か'],
    adviceText: '狙い続ける勇気と切り替える判断を分けて評価します。',
    difficulty: 4,
    tags: ['ナンバー練習', 'CRICKET系'],
  }),
  menu({
    id: 'advanced-release-pressure-check',
    title: 'プレッシャー下リリース確認',
    level: 'advanced',
    gameTypes: ['01', 'COUNT-UP'],
    targetProblems: ['リリースが抜ける', 'イップス気味'],
    durationMinutes: 16,
    purpose: '緊張時に遅れるリリースを早めに検知する。',
    steps: ['目標スコアを決める', '外れた方向を記録する', '抜け感が出たら低負荷へ切り替える'],
    recordItems: ['スコア', '外れ方向', '不安度'],
    evaluationPoints: ['緊張時のズレを言語化できたか', '無理な続行をしていないか'],
    adviceText: '違和感が強い日は成功数より安全な終了判断を優先します。',
    difficulty: 4,
    tags: ['リリース安定', 'メンタル・ルーティン', 'イップス対策'],
  }),
  menu({
    id: 'advanced-dartslive-01-arrange',
    title: 'DARTSLIVE 01アレンジ確認',
    level: 'advanced',
    machineTypes: ['DARTSLIVE', 'BOTH'],
    gameTypes: ['01'],
    targetProblems: ['01が苦手'],
    durationMinutes: 22,
    purpose: '残り点に応じた選択を短時間で決める。',
    steps: ['残り点を想定する', '第一候補と保険を決める', '外した後の残りを確認する'],
    recordItems: ['上がり率', '迷った残り点', '保険ルート'],
    evaluationPoints: ['第一候補に固執していないか', '保険ルートが明確か'],
    adviceText: '公式データ連携なしでも、自分の迷った点数を残せば次の練習に変えられます。',
    difficulty: 5,
    tags: ['01系', 'メンタル・ルーティン'],
  }),
  menu({
    id: 'advanced-phoenix-cricket-finish',
    title: 'PHOENIX Cricket仕上げ',
    level: 'advanced',
    machineTypes: ['PHOENIX', 'BOTH'],
    gameTypes: ['CRICKET'],
    targetProblems: ['クリケットが苦手'],
    durationMinutes: 24,
    purpose: '終盤の閉めと加点判断を磨く。',
    steps: ['終盤状況を想定する', '閉める番号と加点番号を選ぶ', '判断理由を記録する'],
    recordItems: ['マーク数', '判断理由', '終盤ミス'],
    evaluationPoints: ['閉め判断が遅れていないか', '加点に寄りすぎていないか'],
    adviceText: '強い選択と安全な選択を両方持てるようにします。',
    difficulty: 5,
    tags: ['CRICKET系', 'ナンバー練習', 'メンタル・ルーティン'],
  }),
];

export function getPracticeMenuById(id: string) {
  return practiceMenus.find((practiceMenu) => practiceMenu.id === id) ?? null;
}

export function getPracticeMenusByLevel(level: SkillLevelId) {
  return practiceMenus.filter((practiceMenu) => practiceMenu.level === level);
}

export function getPracticeMenusByProblem(problem: string) {
  return practiceMenus.filter((practiceMenu) => practiceMenu.targetProblems.includes(problem));
}

export function getPracticeMenusByMachine(machineType: DartMachine) {
  return practiceMenus.filter((practiceMenu) =>
    matchesMachine(practiceMenu.machineTypes, machineType),
  );
}

export function matchesMachine(machineTypes: DartMachine[], machineType: DartMachine) {
  return (
    machineType === 'BOTH' || machineTypes.includes('BOTH') || machineTypes.includes(machineType)
  );
}
